<?php
/**
 * @package		Arastta eCommerce
 * @copyright	Copyright (C) 2015 Arastta Association. All rights reserved. (arastta.org)
 * @license		GNU General Public License version 3; see LICENSE.txt
 */

// Heading
$_['heading_title']          = 'Các danh mục';

// Text
$_['text_success']           = 'Thành công: Bạn đã sửa các danh mục!';
$_['text_list']              = 'Danh sách danh mục';
$_['text_add']               = 'Thêm danh mục';
$_['text_edit']              = 'Sửa danh mục';
$_['text_default']           = 'Mặc định';

// Column
$_['column_name']            = 'Tên danh mục';
$_['column_sort_order']      = 'Thứ tự sắp xếp';
$_['column_action']          = 'Tác vụ';
$_['column_status']          = 'Status';

// Entry
$_['entry_name']             = 'Tên danh mục';
$_['entry_description']      = 'Mô tả';
$_['entry_meta_title'] 	     = 'Tiêu đề thẻ meta';
$_['entry_meta_keyword'] 	 = 'Từ khóa thẻ meta';
$_['entry_meta_description'] = 'Mô tả thẻ meta';
$_['entry_seo_url']          = 'SEO URL';
$_['entry_parent']           = 'Tên cấp cha';
$_['entry_filter']           = 'Các bộ lọc';
$_['entry_store']            = 'Các gian hàng';
$_['entry_image']            = 'Ảnh';
$_['entry_top']              = 'Trên cùng';
$_['entry_column']           = 'Số cột';
$_['entry_sort_order']       = 'Thứ tự sắp xếp';
$_['entry_status']           = 'Trạng thái';
$_['entry_layout']           = 'Layout ghi đè';
$_['entry_update_menu_name'] = 'Update Menu Name';

// Help
$_['help_filter']            = '(Tự hoàn thành)';
$_['help_seo_url']           = 'Do not enter site name or parent category, just the product URL. Leave empty if you want to be generated by the system automatically based on category name.';
$_['help_top']               = 'Hiển thị trong thanh thực đơn trên cùng. Chỉ áp dụng cho các danh mục cấp cha cao nhất.';
$_['help_column']            = 'Số cột dùng cho 3 danh mục dưới cùng. Chỉ áp dụng cho các danh mục cấp cha cao nhất.';
$_['help_update_menu_name']  = 'If you checked this field update Menu Category name.';

// Error
$_['error_warning']          = 'Chú ý: Vui lòng kiểm tra các lỗi trong biểu mẫu!';
$_['error_permission']       = 'Chú ý: Bạn không có quyền sửa đổi các danh mục!';
$_['error_name']             = 'Tên danh mục phải có từ 2 đến 32 ký tự!';
$_['error_meta_title']       = 'Tiêu đề Meta  phải lớn hơn 3 và ít hơn 255 ký tự!';
$_['error_seo_url']          = 'SEO URL already in use!';