<?php
/**
 * @package		Arastta eCommerce
 * @copyright	Copyright (C) 2015 Arastta Association. All rights reserved. (arastta.org)
 * @license		GNU General Public License version 3; see LICENSE.txt
 */

// Heading
$_['heading_title']         = 'Nhà sản xuất';

// Text
$_['text_success']          = 'Thành công : Bạn đã thay đổi thành công Nhà sản xuất!';
$_['text_list']             = 'Danh sách Nhà sản xuất';
$_['text_add']              = 'Thêm Nhà sản xuất';
$_['text_edit']             = 'Sửa Nhà sản xuất';
$_['text_default']          = 'Mặc định';
$_['text_percent']          = 'Tỷ lệ phần trăm';
$_['text_amount']           = 'Số tiền cố định';

// Column
$_['column_name']           = 'Tên Nhà sản xuất';
$_['column_sort_order']     = 'Thứ tự sắp xếp';
$_['column_action']         = 'Thao tác';
$_['column_status']         = 'Status';

// Entry
$_['entry_name']             = 'Tên Nhà sản xuất';
$_['entry_description']      = 'Description';
$_['entry_meta_title'] 	     = 'Meta Tag Title';
$_['entry_meta_keyword'] 	 = 'Meta Tag Keywords';
$_['entry_meta_description'] = 'Meta Tag Description';
$_['entry_seo_url']          = 'SEO URL';
$_['entry_store']            = 'Stores';
$_['entry_image']            = 'Ảnh';
$_['entry_sort_order']       = 'Thứ tự sắp xếp';
$_['entry_status']           = 'Status';
$_['entry_layout']           = 'Layout Override';
$_['entry_type']             = 'Kiểu';

// Help
$_['help_seo_url']           = 'Do not enter site name, just the manufacturer URL. Leave empty if you want to be generated by the system automatically based on manufacturer name.';

// Error
$_['error_permission']       = 'Cảnh báo: Bạn không có quyền thay đổi thông tin Nhà sản xuất!';
$_['error_name']             = 'Tên Nhà sản xuất từ 2 đến 64 ký tự!';
$_['error_meta_title']       = 'Meta Title must be greater than 3 and less than 255 characters!';
$_['error_seo_url']          = 'SEO URL already in use!';
$_['error_product']          = 'Cảnh báo: Không thể xóa Nhà sản xuất này vì đã có %s sản phẩm liên quan tới Nhà sản xuất này!';