<?php
/**
 * @package		Arastta eCommerce
 * @copyright	Copyright (C) 2015 Arastta Association. All rights reserved. (arastta.org)
 * @credits		See CREDITS.txt for credits and other copyright notices.
 * @license		GNU General Public License version 3; see LICENSE.txt
 */

// Heading
$_['heading_title']          = 'Quản lý sản phẩm';

// Text
$_['text_success']           = 'Thành công: Bạn đã sửa đổi sản phẩm!';
$_['text_list']              = 'Danh sách sản phẩm';
$_['text_add']               = 'Thêm sản phẩm';
$_['text_edit']              = 'Chỉnh sửa sản phẩm';
$_['text_plus']              = '+';
$_['text_minus']             = '-';
$_['text_default']           = 'Mặc định';
$_['text_option']            = 'Tuỳ chọn';
$_['text_option_value']      = 'Giá trị tùy chọn';
$_['text_percent']           = 'Tỷ lệ phần trăm';
$_['text_amount']            = 'Số tiền cố định';

// Column
$_['column_name']            = 'Tên sản phẩm';
$_['column_model']           = 'Mẫu';
$_['column_image']           = 'Hình ảnh';
$_['column_price']           = 'Giá';
$_['column_category']        = 'Category';
$_['column_quantity']        = 'Số lượng';
$_['column_status']          = 'Trạng thái';
$_['column_action']          = 'Thao tác';

// Entry
$_['entry_name']             = 'Tên sản phẩm';
$_['entry_description']      = 'Mô tả';
$_['entry_meta_title'] 	     = 'Thẻ meta Tiêu đề';
$_['entry_meta_keyword'] 	 = 'Thẻ meta Từ khóa ';
$_['entry_meta_description'] = 'Thẻ meta Mô tả';
$_['entry_seo_url']          = 'SEO URL';
$_['entry_model']            = 'Mẫu';
$_['entry_sku']              = 'SKU';
$_['entry_upc']              = 'UPC';
$_['entry_ean']              = 'EAN';
$_['entry_jan']              = 'JAN';
$_['entry_isbn']             = 'ISBN';
$_['entry_mpn']              = 'MPN';
$_['entry_location']         = 'Địa điểm';
$_['entry_shipping']         = 'Yêu cầu giao hàng';
$_['entry_manufacturer']     = 'Nhà sản xuất';
$_['entry_store']            = 'Cửa hàng';
$_['entry_date_available']   = 'Ngày có sẵn';
$_['entry_quantity']         = 'Số lượng';
$_['entry_minimum']          = 'Số lượng tối thiểu';
$_['entry_stock_status']     = 'Trạng thái hết hàng';
$_['entry_price']            = 'Giá';
$_['entry_tax_class']        = 'Loại thuế';
$_['entry_points']           = 'Điểm';
$_['entry_option_points']    = 'Điểm';
$_['entry_subtract']         = 'Trừ trong kho';
$_['entry_weight_class']     = 'Đơn vị trọng lượng';
$_['entry_weight']           = 'Trọng lượng';
$_['entry_dimension']        = 'Kích thước (Dài x Rộng x Cao)';
$_['entry_length_class']     = 'Đơn vị Chiều dài';
$_['entry_length']           = 'Chiều dài';
$_['entry_width']            = 'Chiều rộng';
$_['entry_height']           = 'Chiều cao';
$_['entry_image']            = 'Hình ảnh';
$_['entry_customer_group']   = 'Nhóm khách hàng';
$_['entry_date_start']       = 'Ngày bắt đầu';
$_['entry_date_end']         = 'Ngày kết thúc';
$_['entry_priority']         = 'Mức ưu tiên';
$_['entry_attribute']        = 'Thuộc tính';
$_['entry_attribute_group']  = 'Nhóm thuộc tính';
$_['entry_text']             = 'Văn bản';
$_['entry_option']           = 'Tuỳ chọn';
$_['entry_option_value']     = 'Giá trị tùy chọn';
$_['entry_required']         = 'Được yêu cầu';
$_['entry_status']           = 'Trạng thái';
$_['entry_sort_order']       = 'Sắp xếp thuộc tính';
$_['entry_category']         = 'Danh mục';
$_['entry_filter']           = 'Bộ lọc';
$_['entry_download']         = 'Tải xuống';
$_['entry_related']          = 'Sản phẩm liên quan';
$_['entry_tag']          	 = 'Sản phẩm Tags';
$_['entry_reward']           = 'Điểm thưởng';
$_['entry_layout']           = 'Ghi đè Layout';
$_['entry_recurring']        = 'Hồ sơ định kỳ';

// Help
$_['help_seo_url']           = 'Do not enter site name or category, just the product URL. Leave empty if you want to be generated by the system automatically based on product name.';
$_['help_sku']               = 'Giữ đơn vị trong kho';
$_['help_upc']               = 'Mã sản phẩm chung';
$_['help_ean']               = 'Số điều khoản Châu Âu';
$_['help_jan']               = 'Số điều khoản Nhật Bản';
$_['help_isbn']              = 'International Standard Book Number';
$_['help_mpn']               = 'Manufacturer Part Number';
$_['help_manufacturer']      = '(Tự động hoàn thành)';
$_['help_minimum']           = 'Yêu cầu số lượng đặt hàng tối thiểu';
$_['help_stock_status']      = 'Trạng thái hiển thị khi một sản phẩm hết hàng trong kho';
$_['help_points']            = 'Số điểm cần thiết để mua sản phẩm này. Nếu bạn không muốn sản phẩm này được mua bằng điểm đặt giá trị là 0.';
$_['help_category']          = '(Tự đồng hoàn thành)';
$_['help_filter']            = '(Tự đồng hoàn thành)';
$_['help_download']          = '(Tự đồng hoàn thành)';
$_['help_related']           = '(Tự đồng hoàn thành)';
$_['help_tag']          	 = 'ngăn cách bằng dấu phẩy';

// Error
$_['error_warning']          = 'Chú ý: Vui lòng kiểm tra các lỗi trên form một cách cẩn thận!';
$_['error_permission']       = 'Chú ý: Bạn không có quyền sửa đổi sản phẩm!';
$_['error_name']             = 'Tên sản phẩm phải lớn hơn 3 và ít hơn 255 ký tự!';
$_['error_meta_title']       = 'Meta tiêu đề phải lớn hơn 3 và ít hơn 255 ký tự!';
$_['error_model']            = 'Model sản phẩm phải lớn hơn 1 và ít hơn 64 ký tự!';
$_['error_seo_url']          = 'SEO URL already in use!';
$_['error_tag']              = 'Warning: Already added this tag!';
$_['error_tag_empty']        = 'Warning: Please check the tag must be greater than 1!';